### ISSUE TITLE
[Feature Request] Respawn all killed entities in new round.

### ISSUE THREAD

**Issue by Obada8** [rtxa/HL-Restore-Map#1]
Hi guys,

I made a map which has killing targets for some entities,

I use this plugin [HL Restore Map API v0.6 [Last Update: 04/12/2020]](https://forums.alliedmods.net/showthread.php?t=325178) to reset all entities to original position when new round start, but the problem is this plugin can't respawn the killed entities in previous round, so I need your help to make them respawned again in new round.

Thanks!

**Comment by rtxa** [comment]
Hi Obada,

Depends of how complex is the logic of your map. I don't know how you are doing this, maybe you can send the map and try to explain me the logic. Can you do the same in CS 1.6? Did you see it working in some CS 1.6 map? If not, then it's probably because is something new what you're trying to do and needs to be created from scratch.

Just in case remember there is a list of entities which are available to reset in the front page: https://github.com/rtxa/HL-Restore-Map#-available-classes-for-restoring

**Comment by Obada8** [comment]
Hi rtxa, I edited my map instead of destroy entities I made a `env_render `to hide them and working very well with your plugin.

Just in case in future if you can reset all killed entities ( Ex. `func_wall `killed by door when its opened ) that will be nice! i mean here like your plugin reset all entities to default setting also make all entities to be respawn again.

My map: [here](https://cdn.discordapp.com/attachments/386400966687326209/948699979285921812/cstrike.zip)

Thanks for your work man!

**Comment by rtxa** [comment]
Good that you find a way to achieve the same without killing the entities, but I'm still not getting what do you want to do. 

Maybe you can send me a map (with the source files) were you specifically show me what do you want to do exactly? The map you have send me is too big and I don't know where to start to look, besides it has a LEAK which is the reason the map is fullbright and the FPS are so low.

Thanks for finding the project useful, I never though the restore thing was a feasible thing do but it did.

**Comment by Obada8** [comment]
This is a test map [here](https://cdn.discordapp.com/attachments/386400966687326209/949396601355501658/test.zip)

add for my map source code [here](https://cdn.discordapp.com/attachments/386400966687326209/949397481945444372/worked.jmf).

in this map when door open, the door will kill the `func_rotating`

we need from you to respawn killed `func_rotating`

**Comment by rtxa** [comment]
Maybe you can hide the entity like you did before but you should use `func_wall_toggle` this time to remove the collision and visibility at the same time. It would get restored.

By the moment, I'm not planning to add any new restore stuff that can't be done in CS 1.6 either. The primary goal of this project was making CS 1.6 maps compatible with Half-Life. I've seen a lot of Deathrun/ZE maps of CS 1.6 with complex logic and interactive parts that I though it was impossible to be done. My advice is to try to build your map with the limits you have and to try a lot of CS 1.6 maps to see if what you want is achievable.

If you find maps of CS 1.6 where the restore part doesn't work correctly in HL, you're welcome to make an issue.
